---
k8s-nodes:
  hosts:
    # Put your KVM host connection and settings here
    k8s-node-[0:2]:
      virt_infra_distro_image: CentOS-7-x86_64-GenericCloud.qcow2
      ansible_python_interpreter: /usr/bin/python
      virt_infra_timezone: "Asia/Shanghai"
      virt_infra_disk_cmd:
        - yum -y install yum-plugin-fastestmirror
  vars:
    virt_infra_root_password: password
    virt_infra_disk_size: 40
    virt_infra_ram: 4096
    virt_infra_ram_max: 8192
    virt_infra_cpus: 4
    virt_infra_cpus_max: 8
    virt_infra_state: running
    virt_infra_networks:
      - name: br0
        type: bridge
